$('#slide1').owlCarousel({
    loop:true,
    margin:15,
    nav:true,
    responsive:{
        0:{
            items:1
        },
        480:{
            items:2
        },
        767:{
            items:3
        },
        1000:{
            items:4
        }
    }
})
$('#slide2').owlCarousel({
    loop:true,
    margin:15,
    nav:true,
    responsive:{
        0:{
            items:1
        }
    }
})